[pytest]
testpaths = tests tests_selenium
addopts = -v --html=reports/report.html --self-contained-html
markers =
    login: тесты авторизации
    cart: тесты корзины
    checkout: тесты оформления заказа
    inventory: тесты каталога товаров
    selenium: тесты на Selenium (smoke)
